### ISSUE TITLE
Blackjax 0.3 is no longer compatible with recent JAX

### ISSUE THREAD

**Issue by EiffL** [austinpeel/herculens#21]
The code can in principle run with blackjax v0.3, but v0.3 is no longer compatible with current JAX.

The API of blackjax has changed in v0.4, so there is a little bit of rewriting to do in https://github.com/austinpeel/herculens/blob/6c35e2c5172de3c4428114b403ce8751983035fc/herculens/Inference/sampling.py#L37

to make it work with the new versions. It shouldn't be difficult.

**Comment by rlouf** [comment]
Two differences. Now the high-level API works as:

```python
import blackjax

nuts = blackjax.nuts(logprobs_fn, step_size, inverse_mass_matrix)
init_state = nuts.init(position)
new_state, info = nuts.step(rng_key, state)
```

And the adaptation:

```python
window_adaptation = blackjax.window_adaptation(blackjax.nuts, logprob_fn, num_steps=1000)
state, kernel, _ = window_adaptation.run(rng_key, position)

# you can directly use the tuned kernel
_, rng_key = jax.random.split(rng_key)
new_state, info = kernel(rng_key, state)
```

I *strongly* recommend to pin the blackjax version in your `requirements.txt` or `setup.py` until v1 is released.

**Comment by aymgal** [comment]
The PR #22 should fix the issue, so I'm closing it. Thanks guys
